In [2]:
import numpy as np

In [5]:
mylist = [1, 2, 3]
# normal python list, not np array
type(mylist) 

list

In [7]:
arr = np.array(mylist)
type(arr), arr

(numpy.ndarray, array([1, 2, 3]))

In [9]:
arr.shape

(3,)

In [11]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(6) + 3, np.ones((2, 3))

(array([3., 3., 3., 3., 3., 3.]), array([[1., 1., 1.],
        [1., 1., 1.]]))

In [17]:
# inclusive start, end, amount of number you want, evenly spaced
np.linspace(0, 10, 20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [18]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

## generate random numbers to play with

In [21]:
# random number, uniform distribution between 0, 1
np.random.rand(2), np.random.rand(6, 2)

(array([0.74452142, 0.05261933]), array([[0.54860743, 0.28007983],
        [0.78275952, 0.19239263],
        [0.6614801 , 0.16929398],
        [0.32212304, 0.01008761],
        [0.5095832 , 0.20250738],
        [0.18759861, 0.29551873]]))

In [23]:
# random number, normal distribution
np.random.randn(3)

array([-1.21593821,  1.00897956,  0.03204514])

In [25]:
# specify your own mean and standard deviation
np.random.normal(0, 1, (2, 3))

array([[ 0.63926768, -0.93771273, -0.7182865 ],
       [ 0.02241726, -0.4702652 , -0.04043196]])

In [30]:
# randomly choose 10 numbers between 1, 100
np.random.randint(1, 100, 10)

array([88, 24,  3, 22, 53,  2, 88, 30, 38,  2])

In [31]:
# reproduce random numbers -- setting seed
np.random.seed(42)
np.random.randint(1, 100, 10)

array([52, 93, 15, 72, 61, 21, 83, 87, 75, 75])

In [36]:
ranarr = np.random.randint(1, 50, 10)
ranarr

array([44, 25, 49, 27, 42, 28, 16, 15, 47, 44])

In [38]:
ranarr.reshape(2, 5)

array([[44, 25, 49, 27, 42],
       [28, 16, 15, 47, 44]])

In [41]:
ranarr.max()

49

In [43]:
ranarr.argmax(), ranarr.argmin()

(2, 7)

In [46]:
ranarr.dtype

dtype('int64')

## Indexing

In [47]:
arr = np.arange(0, 10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
# point to original array
slice_of_arr = arr[:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [51]:
slice_of_arr[:] = 99
slice_of_arr, arr

(array([99, 99, 99, 99, 99]), array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9]))

In [52]:
# create a copy in the memory
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy, arr

(array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100]),
 array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9]))

In [60]:
arr_2d = np.arange(5, 50, 5)
arr_2d = arr_2d.reshape(3, 3)
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [62]:
# get subset of the matrix
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

## Conditional selection

In [65]:
arr = np.arange(2, 10)
arr

array([2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
bool_arr = arr > 4
bool_arr

array([False, False, False,  True,  True,  True,  True,  True])

In [70]:
arr[bool_arr]

array([5, 6, 7, 8, 9])

In [72]:
arr[arr > 4]

array([5, 6, 7, 8, 9])

In [73]:
arr.sum(), arr.min()


(44, 2)

In [74]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [78]:
arr_2d.sum(axis=0), arr_2d.sum(axis=1), arr_2d.sum()

(array([60, 75, 90]), array([ 30,  75, 120]), 225)