#some of the most fundamental concepts of tensors using Tensorflow 

In [1]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [2]:
# create tensors
scalar = tf.constant(7);
scalar;
print(scalar)

tf.Tensor(7, shape=(), dtype=int32)


In [3]:
# check the number of dims of a tensor (ndim)
scalar.ndim

0

In [4]:
# vector
vector = tf.constant([10, 10])
print(vector)
vector.ndim

tf.Tensor([10 10], shape=(2,), dtype=int32)


1

In [5]:
import numpy as np
a = np.arange(12)  
# print (a)             # a 现只有一个维度
# 现在调整其大小
b = a.reshape(2, 3, 2)  # b 现在拥有三个维度
# b = b[:2, ..., :1]
print(b.ndim)
print (np.concatenate(b, axis=1))

3
[[ 0  1  6  7]
 [ 2  3  8  9]
 [ 4  5 10 11]]


In [6]:
# create a matrix
matrix = tf.constant([[10, 7,10],
                      [7, 10, 10],
                      [7, 10, 10]])
matrix2 = tf.constant([[[10, 7,10], 
                        [7, 10, 10]],
                      [[7, 10, 10], 
                       [7, 10, 10]],
                      [[7, 10, 10], 
                       [7, 10, 10]]])
matrix.ndim

2

In [7]:
# another matrix
another_matirx = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matirx

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [8]:
# create a random tensor
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))

# shuffle the order of elements in a tensor
# print(random_1)
# tf.random.shuffle(random_1)
tf.random.set_seed(42);
print(tf.random.shuffle(another_matirx))

tf.Tensor(
[[ 3.  2.]
 [ 8.  9.]
 [10.  7.]], shape=(3, 2), dtype=float16)


In [9]:
ones = tf.ones([2, 3])
ones
zeros = tf.zeros([3, 2])
print(zeros)

print(tf.reshape(zeros, shape=(2, 3)))
print(zeros)

tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


In [10]:
matrix1 = tf.range(12)
print("matrix1", matrix1)
matrix1 = tf.reshape(matrix1, [4, 3])
print("matrix1 after reshape", matrix1)
matrix2 = tf.constant(matrix1, shape=(2, 6))
print(matrix2)

import numpy as np
numpy_a = np.arange(24)
numpy_a
A = tf.constant(numpy_a, shape=(2, 3, 4))
print(A)


matrix1 tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11], shape=(12,), dtype=int32)
matrix1 after reshape tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]], shape=(2, 6), dtype=int32)
tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int64)


In [11]:
print("matrix is ", matrix1, "\n")
A = matrix1
print(tf.matmul(tf.transpose(A), A), "\n")
print(tf.tensordot(tf.transpose(A), A, axes=1))

matrix is  tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int32) 

tf.Tensor(
[[126 144 162]
 [144 166 188]
 [162 188 214]], shape=(3, 3), dtype=int32) 

tf.Tensor(
[[126 144 162]
 [144 166 188]
 [162 188 214]], shape=(3, 3), dtype=int32)


In [12]:
B = tf.reshape(A, [2, 3, 2])
print(B)
# print(B[:, :2, :1])

tf.Tensor(
[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]], shape=(2, 3, 2), dtype=int32)


# aggregation + cast


In [13]:
print(A)
A = tf.cast(A, dtype=tf.float16)
print(A)

tf.Tensor(
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]], shape=(4, 3), dtype=int32)
tf.Tensor(
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]], shape=(4, 3), dtype=float16)


In [14]:
# get absolute values
M = tf.constant([[-1, 3]]);
tf.abs(M)

# create a random tensor with values between 10, 100 of size 50
B = tf.constant(np.random.randint(0, 100, size=50))
B

# find the max, min, mean, sum 
tf.reduce_max(B), tf.reduce_min(B), tf.reduce_mean(B)

tf.size(B), B.shape, B.ndim
print(tf.reduce_min(B), np.min(B))

tf.Tensor(0, shape=(), dtype=int64) 0


In [25]:
# find variance, standard deviation
import tensorflow_probability as tfp;
print(A)
var = tfp.stats.variance(A)
std = tf.math.reduce_std(tf.cast(A, dtype=tf.float32))
var2 = tf.math.reduce_variance(tf.cast(A, dtype=tf.float32))
var, var2,std


(<tf.Tensor: shape=(3,), dtype=float16, numpy=array([11.25, 11.25, 11.25], dtype=float16)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=11.916667>,
 <tf.Tensor: shape=(), dtype=float32, numpy=3.4520526>)

## find argmin, argmax

In [29]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [43]:
tf.argmax(F) # index
assert F[tf.argmax(F)] == tf.reduce_max(F)

print(A)
tf.argmax(A, axis=1)

tf.Tensor(
[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]], shape=(4, 3), dtype=float16)


<tf.Tensor: shape=(4,), dtype=int64, numpy=array([2, 2, 2, 2])>

squeezing a tensor (removing all single dim)


In [51]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[16]), shape=(1, 1, 1, 16))
print(G, "\n")
G_squeezed = tf.squeeze(G)
print(G_squeezed, "\n", G_squeezed.shape)


tf.Tensor(
[[[[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
    0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
    0.13318717 0.5480639  0.5746088  0.8996835 ]]]], shape=(1, 1, 1, 16), dtype=float32) 

tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835 ], shape=(16,), dtype=float32) 
 (16,)


# one hot encoding tensors

In [61]:
some_list = [0, 1, 2, 1]
tf.one_hot(some_list, depth=4, on_value=999, off_value=0)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[999,   0,   0,   0],
       [  0, 999,   0,   0],
       [  0,   0, 999,   0],
       [  0, 999,   0,   0]], dtype=int32)>

# square, squaer root, log

In [71]:
H = tf.range(1, 10)
square = tf.square(H)
sqrt = tf.sqrt(tf.cast(H, dtype=tf.float32))
log = tf.math.log(tf.cast(H, dtype=tf.float16))
square, sqrt, log

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([0.99999994, 1.4142134 , 1.7320508 , 1.9999999 , 2.236068  ,
        2.4494896 , 2.6457512 , 2.8284268 , 3.        ], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float16, numpy=
 array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
        2.197 ], dtype=float16)>)

# numpy and tensorflow
tensorflow interacts with numpy arrays

🔑 **Note** one of the main differences between tensorflow and numpy array is that tf tensor can be run on a gpu or tpu for fast numerical computing

tpu: ai accelerator asic specifically for nn ml


In [76]:
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [82]:
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [83]:
J.numpy()

array([ 3.,  7., 10.])

# finding access to gpus

In [3]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [6]:
!nvidia-smi # what gpu is using

# cuda -- basically a driver, kinda interface between gpu and tf code that makes the tf code run fast 

Wed Aug 18 17:17:47 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.57.02    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P8    31W / 149W |      3MiB / 11441MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

🔑 **Note** If you have access to a CUDA-ennabled GPU, tf will automatically use it whenever possible.