## Use Pytorch as tensor array library

In [2]:
import torch
import numpy as np

In [3]:
torch.__version__

'1.9.0+cu102'

## Convert to tensor

In [4]:
arr = np.arange(1, 10)
arr, type(arr)

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [5]:

x = torch.from_numpy(arr)
x, type(x)

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Tensor)

In [6]:
torch.as_tensor(arr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x.dtype

torch.int64

In [8]:
arr2d = np.arange(0.0, 12.0)
x2 = torch.from_numpy(arr2d.reshape(4, 3))
x2

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)

In [9]:
arr
arr[0] = 99
arr, x

(array([99,  2,  3,  4,  5,  6,  7,  8,  9]),
 tensor([99,  2,  3,  4,  5,  6,  7,  8,  9]))

In [10]:
# create a copy
x3 = torch.tensor(arr)
x3


tensor([99,  2,  3,  4,  5,  6,  7,  8,  9])

In [11]:
x3[0] = 100
x3, arr

(tensor([100,   2,   3,   4,   5,   6,   7,   8,   9]),
 array([99,  2,  3,  4,  5,  6,  7,  8,  9]))

In [12]:
arr

array([99,  2,  3,  4,  5,  6,  7,  8,  9])

In [16]:
torch.Tensor(arr).dtype

torch.float32

In [17]:
torch.tensor(arr).dtype

torch.int64

In [19]:
torch.LongTensor(arr).dtype

torch.int64

## creating tensor from scratch

In [21]:
torch.empty(6)

tensor([-9.6308e-15,  3.0718e-41,  0.0000e+00,  0.0000e+00,  0.0000e+00,
         0.0000e+00])

In [23]:
torch.arange(0, 10, 2).reshape(5, 1)

tensor([[0],
        [2],
        [4],
        [6],
        [8]])

In [25]:
x = torch.tensor(arr, dtype=torch.int)
x

tensor([99,  2,  3,  4,  5,  6,  7,  8,  9], dtype=torch.int32)

In [31]:
# change x's type
x = x.type(torch.float32)
x.type()

'torch.FloatTensor'

## random numbers

In [29]:
x.reshape(3, 3)

tensor([[99,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]])

In [32]:
torch.rand_like(x)

tensor([0.7653, 0.7732, 0.7678, 0.2425, 0.6989, 0.0770, 0.7364, 0.8560, 0.3169])

In [33]:
torch.randn_like(x)

tensor([-0.7531, -0.9311, -0.1435, -0.9114,  0.1259,  0.6236,  0.6118,  0.4243,
         1.0214])

In [34]:
torch.randint_like(x, 2, 10)

tensor([7., 6., 2., 3., 3., 2., 5., 4., 2.])

## operations -- shaping and slicing

In [36]:
x = torch.arange(6).reshape(3, 2)
x

tensor([[0, 1],
        [2, 3],
        [4, 5]])

In [37]:
# indexing
x[:, 1]

tensor([1, 3, 5])

In [38]:
# slicing
x[:, 1:]

tensor([[1],
        [3],
        [5]])

In [42]:
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### view, reshape

In [43]:
x.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [45]:
x.reshape(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

### view reflects the most current data

In [48]:
z = x.view(2, 5)
z

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [52]:
x[0] = 99
z

tensor([[99,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [51]:
# infer the correct size using -1
x.view(-1, 5)

tensor([[99,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

In [53]:
## adopt another tensor's shape
x.view_as(z)

tensor([[99,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]])

## arithmetics

In [63]:
a = torch.tensor([1,2,3], dtype=torch.float)
b = torch.tensor([4,5,6], dtype=torch.float)

In [64]:
a.mul(b), a*3, a

(tensor([ 4., 10., 18.]), tensor([3., 6., 9.]), tensor([1., 2., 3.]))

In [65]:
# reassign result to a
print(a)
a.mul_(b)
a

tensor([1., 2., 3.])


tensor([ 4., 10., 18.])

###  multiplication

In [67]:
# dot product
a, b, a.dot(b)

(tensor([ 4., 10., 18.]), tensor([4., 5., 6.]), tensor(174.))

In [69]:
a = torch.tensor([[0,2,4],[1,3,5]], dtype=torch.float)
b = torch.tensor([[6,7],[8,9],[10,11]], dtype=torch.float)
a.shape, b.shape

(torch.Size([2, 3]), torch.Size([3, 2]))

In [71]:
# matrix multiplication
torch.mm(a, b), a @ b

(tensor([[56., 62.],
         [80., 89.]]), tensor([[56., 62.],
         [80., 89.]]))

### L2 or Euclidian Norm
See <a href='https://pytorch.org/docs/stable/torch.html#torch.norm'><strong><tt>torch.norm()</tt></strong></a>

The <a href='https://en.wikipedia.org/wiki/Norm_(mathematics)#Euclidean_norm'>Euclidian Norm</a> gives the vector norm of $x$ where $x=(x_1,x_2,...,x_n)$.<br>
It is calculated as<br>

${\displaystyle \left\|{\boldsymbol {x}}\right\|_{2}:={\sqrt {x_{1}^{2}+\cdots +x_{n}^{2}}}}$


When applied to a matrix, <tt>torch.norm()</tt> returns the <a href='https://en.wikipedia.org/wiki/Matrix_norm#Frobenius_norm'>Frobenius norm</a> by default.

In [73]:
x = torch.tensor([2.,5.,8.,14.])
x.norm()

tensor(17.)

In [75]:
x.numel(), len(x)

(4, 4)

In [77]:
a = torch.arange(6).reshape(2, -1)
a

tensor([[0, 1, 2],
        [3, 4, 5]])

In [78]:
a.numel(), len(a)

(6, 2)